const STORAGE_KEY='whiskylogg_premium_v1_1';
const TYPES=['Whisky','Single Malt Scotch','Blended Scotch','Bourbon','Rye Whiskey','Irish Whiskey','Japanese Whisky','Rum','Dark Rum','Aged Rum','Agricole Rum','Cachaça','Cognac','Armagnac','Brandy','Calvados','Tequila','Mezcal','Gin','Vodka','Aquavit','Grappa','Pisco','Liqueur','Amaro','Baijiu','Shochu','Annet'];
const state=loadState(); let pendingBottleImage='', pendingTastingImage='', pendingWishlistImage='';
document.addEventListener('DOMContentLoaded',()=>{initSelects();initNav();initForms();initSettings();renderAll();seedDates();registerServiceWorker();});
function loadState(){const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):{bottles:[],tastings:[],wishlist:[]}} function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)} function money(n){return `${Math.round(Number(n||0)).toLocaleString('no-NO')} kr`} function ml(n){return `${Math.round(Number(n||0)).toLocaleString('no-NO')} ml`} function avg(arr){return arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:0}
function byTypeSummary(){const map={};state.bottles.forEach(b=>{const rem=bottleRemaining(b.id);if(!map[b.type]) map[b.type]={cost:0,volume:0,count:0};map[b.type].cost+=Number(b.price||0)*Number(b.quantity||1);map[b.type].volume+=rem;map[b.type].count+=Number(b.quantity||1)});return Object.entries(map).sort((a,b)=>b[1].volume-a[1].volume)}
function bottleRemaining(id){const bottle=state.bottles.find(b=>b.id===id);if(!bottle) return 0;const start=Number(bottle.bottleVolume||0)*Number(bottle.quantity||1);const used=state.tastings.filter(t=>t.bottleId===id&&t.source==='Egen flaske').reduce((s,t)=>s+Number(t.volume||0),0);return Math.max(0,start-used)}
function bottleScore(id){const ts=state.tastings.filter(t=>t.bottleId===id);return avg(ts.map(t=>Number(t.score||0)))} function bottleLastTasted(id){const ts=state.tastings.filter(t=>t.bottleId===id).sort((a,b)=>String(b.date).localeCompare(String(a.date)));return ts[0]?.date||'—'}
function spiritOptionsHTML(){return TYPES.map(t=>`<option>${t}</option>`).join('')} function initSelects(){document.getElementById('spiritTypeSelect').innerHTML=spiritOptionsHTML();document.getElementById('wishlistTypeSelect').innerHTML=spiritOptionsHTML();refreshBottleSelect()}
function refreshBottleSelect(){const select=document.getElementById('tastingBottleSelect'); if(!select) return; select.innerHTML=state.bottles.length?state.bottles.map(b=>`<option value="${b.id}">${escapeHtml(b.name)} — ${escapeHtml(b.type)}</option>`).join(''):'<option value="">Ingen flasker ennå</option>'}
function initNav(){document.querySelectorAll('[data-go]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.go)))}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.nav-btn').forEach(v=>v.classList.toggle('active',v.dataset.go===name));window.scrollTo({top:0,behavior:'smooth'})}
function initForms(){handleImageInput(document.querySelector('#bottleForm input[name="image"]'),'#bottlePreview',data=>pendingBottleImage=data);handleImageInput(document.querySelector('#tastingForm input[name="image"]'),'#tastingPreview',data=>pendingTastingImage=data);handleImageInput(document.querySelector('#wishlistForm input[name="image"]'),'#wishlistPreview',data=>pendingWishlistImage=data);
 document.getElementById('bottleForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);state.bottles.unshift({id:uid(),name:data.get('name'),distillery:data.get('distillery')||'',type:data.get('type')||'Whisky',abv:Number(data.get('abv')||0),bottleVolume:Number(data.get('bottleVolume')||700),price:Number(data.get('price')||0),quantity:Number(data.get('quantity')||1),purchaseDate:data.get('purchaseDate')||'',purchasePlace:data.get('purchasePlace')||'',region:data.get('region')||'',notes:data.get('notes')||'',image:pendingBottleImage||''});saveState();e.target.reset();clearPreview('#bottlePreview');pendingBottleImage='';refreshBottleSelect();renderAll();showView('inventory')});
 document.getElementById('tastingForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);const nose=Number(data.get('nose')||0), palate=Number(data.get('palate')||0), finish=Number(data.get('finish')||0), balance=Number(data.get('balance')||0);const score=Number(((nose+palate+finish+balance)/4).toFixed(1));state.tastings.unshift({id:uid(),bottleId:data.get('bottleId'),date:data.get('date'),volume:Number(data.get('volume')||20),source:data.get('source')||'Egen flaske',nose,palate,finish,balance,score,water:data.get('water')||'Nei',noseNotes:data.get('noseNotes')||'',tasteNotes:data.get('tasteNotes')||'',finishNotes:data.get('finishNotes')||'',overallNotes:data.get('overallNotes')||'',image:pendingTastingImage||''});saveState();e.target.reset();seedDates();clearPreview('#tastingPreview');pendingTastingImage='';renderAll();showView('tastings')});
 document.getElementById('wishlistForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);state.wishlist.unshift({id:uid(),name:data.get('name'),type:data.get('type'),targetPrice:Number(data.get('targetPrice')||0),priority:data.get('priority'),notes:data.get('notes')||'',image:pendingWishlistImage||''});saveState();e.target.reset();clearPreview('#wishlistPreview');pendingWishlistImage='';renderAll()});
 document.getElementById('inventorySearch').addEventListener('input',renderInventoryList);document.getElementById('tastingSearch').addEventListener('input',renderTastingsList)}
function handleImageInput(input, previewSelector, cb){input.addEventListener('change',async e=>{const file=e.target.files[0];if(!file) return;const data=await resizeImage(file,1200,.82);cb(data);const preview=document.querySelector(previewSelector);preview.src=data;preview.classList.remove('hidden')})}
function clearPreview(selector){const el=document.querySelector(selector);el.src='';el.classList.add('hidden')}
function resizeImage(file,maxSize=1200,quality=.82){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const ratio=Math.min(1,maxSize/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',quality))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
function initSettings(){document.getElementById('exportBtn').addEventListener('click',exportData);document.getElementById('backupBtn').addEventListener('click',()=>showView('settings'));document.getElementById('importInput').addEventListener('change',importData);document.getElementById('resetBtn').addEventListener('click',()=>{if(!confirm('Slette all data? Dette kan ikke angres.')) return; state.bottles=[];state.tastings=[];state.wishlist=[];saveState();renderAll();refreshBottleSelect();showView('home')});document.getElementById('seedBtn').addEventListener('click',seedExamples)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});downloadBlob(blob,`whiskylogg-backup-${new Date().toISOString().slice(0,10)}.json`)}
function importData(e){const file=e.target.files[0];if(!file) return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);state.bottles=Array.isArray(data.bottles)?data.bottles:[];state.tastings=Array.isArray(data.tastings)?data.tastings:[];state.wishlist=Array.isArray(data.wishlist)?data.wishlist:[];saveState();refreshBottleSelect();renderAll();showView('home');alert('Backup importert.')}catch{alert('Kunne ikke lese backup-filen.')}};reader.readAsText(file)}
function downloadBlob(blob, filename){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function renderAll(){refreshBottleSelect();renderHome();renderInventory();renderInventoryList();renderTastingsList();renderWishlist()}
function renderHome(){const totalCost=state.bottles.reduce((s,b)=>s+Number(b.price||0)*Number(b.quantity||1),0);const totalVol=state.bottles.reduce((s,b)=>s+bottleRemaining(b.id),0);document.getElementById('totalCost').textContent=money(totalCost);document.getElementById('totalVolume').textContent=ml(totalVol);document.getElementById('bottleCount').textContent=String(state.bottles.length);document.getElementById('tastingCount').textContent=String(state.tastings.length);const recent=state.tastings.slice(0,5);document.getElementById('recentTastings').innerHTML=recent.length?recent.map(t=>{const bottle=state.bottles.find(b=>b.id===t.bottleId);return `<div class="summary-row"><div><strong>${escapeHtml(bottle?.name||'Ukjent flaske')}</strong><div class="meta">${escapeHtml(t.date||'—')} · ${ml(t.volume)} · ${escapeHtml(t.source)}</div></div><div class="score-badge">${t.score}</div></div>`}).join(''):'<div class="empty">Ingen smakinger registrert ennå.</div>';const entries=byTypeSummary();document.getElementById('typeSummary').innerHTML=entries.length?entries.map(([type,info])=>`<div class="type-row"><div><strong>${escapeHtml(type)}</strong><div class="meta">${info.count} flaske(r)</div></div><div class="submeta">${money(info.cost)} · ${ml(info.volume)}</div></div>`).join(''):'<div class="empty">Ingen flasker registrert ennå.</div>'}
function renderInventory(){const totalCost=state.bottles.reduce((s,b)=>s+Number(b.price||0)*Number(b.quantity||1),0);const totalVol=state.bottles.reduce((s,b)=>s+bottleRemaining(b.id),0);document.getElementById('inventoryCost').textContent=money(totalCost);document.getElementById('inventoryVolume').textContent=ml(totalVol);const entries=byTypeSummary();document.getElementById('inventoryByType').innerHTML=entries.length?entries.map(([type,info])=>`<div class="type-row"><div><strong>${escapeHtml(type)}</strong></div><div class="submeta">${money(info.cost)} · ${ml(info.volume)}</div></div>`).join(''):'<div class="empty">Ingen data ennå.</div>'}
function renderInventoryList(){const q=document.getElementById('inventorySearch').value.toLowerCase().trim();const bottles=state.bottles.filter(b=>[b.name,b.distillery,b.type,b.region].join(' ').toLowerCase().includes(q));document.getElementById('inventoryList').innerHTML=bottles.length?bottles.map(b=>bottleCard(b)).join(''):'<div class="empty">Ingen flasker matcher søket.</div>';bindDeleteButtons()}
function bottleCard(b){const remaining=bottleRemaining(b.id), score=bottleScore(b.id), last=bottleLastTasted(b.id);const image=b.image?`<img class="thumb" src="${b.image}" alt="${escapeAttr(b.name)}">`:'';const klass=b.image?'item-card':'item-card no-image';return `<div class="${klass}">${image}<div><div class="item-title">${escapeHtml(b.name)}</div><div class="meta">${escapeHtml(b.type)} · ${escapeHtml(b.distillery||'Ukjent produsent')}</div><div class="meta">${escapeHtml(b.region||'—')} · ${b.abv?`${b.abv}%`:'ABV ukjent'}</div><div class="submeta">Sist smakt: ${escapeHtml(last)}</div><div class="submeta">${escapeHtml(b.purchasePlace||'—')}</div><div class="tags"><span class="pill">${ml(remaining)} igjen</span><span class="pill">${money(Number(b.price||0)*Number(b.quantity||1))}</span>${score?`<span class="pill ok">Score ${score.toFixed(1)}</span>`:''}</div></div><div class="item-side"><button class="ghost-btn" data-delete-bottle="${b.id}">Slett</button></div></div>`}
function renderTastingsList(){const q=document.getElementById('tastingSearch').value.toLowerCase().trim();const tastings=state.tastings.filter(t=>{const bottle=state.bottles.find(b=>b.id===t.bottleId);return [bottle?.name,t.noseNotes,t.tasteNotes,t.finishNotes,t.overallNotes].join(' ').toLowerCase().includes(q)});document.getElementById('tastingsList').innerHTML=tastings.length?tastings.map(t=>tastingCard(t)).join(''):'<div class="empty">Ingen smakinger matcher søket.</div>';bindDeleteButtons()}
function tastingCard(t){const bottle=state.bottles.find(b=>b.id===t.bottleId);const image=t.image?`<img class="thumb" src="${t.image}" alt="smaking">`:'';const klass=t.image?'item-card':'item-card no-image';return `<div class="${klass}">${image}<div><div class="item-title">${escapeHtml(bottle?.name||'Ukjent flaske')}</div><div class="meta">${escapeHtml(t.date||'—')} · ${ml(t.volume)} · ${escapeHtml(t.source)}</div><div class="tags"><span class="pill">Nese ${t.nose}</span><span class="pill">Smak ${t.palate}</span><span class="pill">Finish ${t.finish}</span><span class="pill">Helhet ${t.balance}</span><span class="pill ok">Score ${t.score}</span></div><div class="submeta">Vann: ${escapeHtml(t.water)}</div>${noteBlock('Nese',t.noseNotes)}${noteBlock('Smak',t.tasteNotes)}${noteBlock('Finish',t.finishNotes)}${noteBlock('Helhet',t.overallNotes)}</div><div class="item-side"><button class="ghost-btn" data-delete-tasting="${t.id}">Slett</button></div></div>`}
function noteBlock(label,text){return text?`<div class="submeta"><strong>${escapeHtml(label)}:</strong> ${escapeHtml(text)}</div>`:''}
function renderWishlist(){document.getElementById('wishlistList').innerHTML=state.wishlist.length?state.wishlist.map(w=>wishlistCard(w)).join(''):'<div class="empty">Ønskelisten er tom.</div>';bindDeleteButtons()}
function wishlistCard(w){const image=w.image?`<img class="thumb" src="${w.image}" alt="${escapeAttr(w.name)}">`:'';const klass=w.image?'item-card':'item-card no-image';const prioClass=w.priority==='Høy'?'ok':(w.priority==='Lav'?'red':'');return `<div class="${klass}">${image}<div><div class="item-title">${escapeHtml(w.name)}</div><div class="meta">${escapeHtml(w.type)} · Målpris ${money(w.targetPrice||0)}</div><div class="tags"><span class="pill ${prioClass}">${escapeHtml(w.priority)}</span></div>${w.notes?`<div class="submeta">${escapeHtml(w.notes)}</div>`:''}</div><div class="item-side"><button class="ghost-btn" data-delete-wishlist="${w.id}">Slett</button></div></div>`}
function bindDeleteButtons(){document.querySelectorAll('[data-delete-bottle]').forEach(btn=>btn.onclick=()=>{if(!confirm('Slette flaske? Tilhørende smakinger slettes også.')) return;const id=btn.dataset.deleteBottle;state.bottles=state.bottles.filter(b=>b.id!==id);state.tastings=state.tastings.filter(t=>t.bottleId!==id);saveState();refreshBottleSelect();renderAll()});document.querySelectorAll('[data-delete-tasting]').forEach(btn=>btn.onclick=()=>{if(!confirm('Slette smaking?')) return;state.tastings=state.tastings.filter(t=>t.id!==btn.dataset.deleteTasting);saveState();renderAll()});document.querySelectorAll('[data-delete-wishlist]').forEach(btn=>btn.onclick=()=>{if(!confirm('Slette ønskelistepost?')) return;state.wishlist=state.wishlist.filter(w=>w.id!==btn.dataset.deleteWishlist);saveState();renderAll()})}
function seedDates(){const today=new Date().toISOString().slice(0,10);const tDate=document.querySelector('#tastingForm input[name="date"]');const bDate=document.querySelector('#bottleForm input[name="purchaseDate"]');if(tDate && !tDate.value) tDate.value=today; if(bDate && !bDate.value) bDate.value=today}
function seedExamples(){if(state.bottles.length && !confirm('Dette legger til eksempelflasker i tillegg til eksisterende data. Fortsette?')) return; [{name:'Woodford Reserve Double Oaked',distillery:'Brown-Forman',type:'Bourbon',abv:43.2,bottleVolume:700,price:699,quantity:1,purchasePlace:'Eksempel',region:'Kentucky',notes:'Dyp eik, karamell, vanilje',image:''},{name:'Elijah Craig Small Batch',distillery:'Heaven Hill',type:'Bourbon',abv:47,bottleVolume:700,price:549,quantity:1,purchasePlace:'Eksempel',region:'Kentucky',notes:'Klassisk bourbonprofil',image:''},{name:'Diplomático Reserva Exclusiva',distillery:'Destilerías Unidas',type:'Aged Rum',abv:40,bottleVolume:700,price:499,quantity:1,purchasePlace:'Eksempel',region:'Venezuela',notes:'Søt, mørk, fyldig',image:''},{name:'Rémy Martin VSOP',distillery:'Rémy Martin',type:'Cognac',abv:40,bottleVolume:700,price:579,quantity:1,purchasePlace:'Eksempel',region:'Cognac',notes:'Frukt, krydder, eik',image:''}].forEach(e=>state.bottles.push({id:uid(),purchaseDate:'',...e}));saveState();refreshBottleSelect();renderAll();showView('inventory')}
function escapeHtml(str=''){return String(str).replace(/[&<>"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[s]))} function escapeAttr(str=''){return escapeHtml(str).replace(/'/g,'&#39;')}
function registerServiceWorker(){if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{})}
